name: Ping Render App

on:
  schedule:
    - cron: "*/13 * * * *"   # every 13 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping server
        run: |
          curl -X GET https://baskito-grocery-app-current.onrender.com
